CREATE OR REPLACE TABLE ANKIT_DB.STAGING.FACT_SUPERSTORE AS
SELECT 
    ROW_ID,
    ORDER_ID,
    ORDER_DATE,
    SHIP_DATE,
    CUSTOMER_ID,
    POSTAL_CODE,
    PRODUCT_ID,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT,
    SHIPPING_COST
FROM ANKIT_DB.STAGING.SUPERSTORE;
